name: run piplean trinig

# Controls whengh the worGHkfgdgfdsdfsdflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main , develop ]
  pull_request:
    branches: [ main ]

  
  workflow_dispatch:

# A workflow run is made up of one fgf ordf more jobs that can run sequentially or in parallel

jobs:

  buildImage:
    name: Build and Deploy image of training to ECR
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2


    - name: telchage model
      run: |
        pip install gsutil
        gsutil cp -r gs://mlflow-esi/model_mlflow .
        ls -la
    - name: cp requerement txt
      run: |
        mkdir api_contener/api
        cp model_mlflow/requirements.txt api_contener
        cp API/app.py api_contener/api
        cp -r API/uploads api_contener/api 
        cp -r API/static api_contener/api
        cp -r API/templates api_contener/api
        cp -r API/model_mlflow api_contener/api   
        
        
         
   
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build, tag, and push image to Amazon ECR
      env:
        # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: training_imag
        IMAGE_TAG: latest
      run: |
        # docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./environment_setup/training_container
        # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker build -t khaldi22/api_imag:latest api_contener
          docker push khaldi22/api_imag:latest 